import Head from "next/head";
import Posts from "../components/posts/Posts";
import Suggestions from "../components/home/Suggestions";
import MiniProfile from "../components/home/MiniProfile";
import Header from "../components/layout/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>instago</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" ml md:px-8 pb-6 md:py-6">
        <Header />
        <div className="grid grid-cols-1 md:grid-cols-[60%,40%] row-88">
          <section className="">
            {/* <Stories /> */}
            <Posts />
          </section>
          <section className="max-md:hidden">
            <div className="sticky top-6">
              <MiniProfile />
              <Suggestions />
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
